#!/usr/bin/env bash

set_keyboard_layout() {
  op_title="${key_op_msg}"
  while (true); do
    keyboard="$(dialog --nocancel --ok-button "${ok}" --menu "${keys_msg}" 18 60 10 \
      "de" "German" \
      "el" "Greek" \
      "es" "Spanish" \
      "fr" "French" \
      "hu" "Hungarian" \
      "it" "Italian" \
      "pt-latin9" "Portugal" \
      "ro" "Romanian" \
      "ru" "Russian" \
      "slovene" "Slovenian" \
      "sv" "Swedish" \
      "uk" "United Kingdom" \
      "us" "United States" \
      "${other}" "${other}-keymaps" 3>&1 1>&2 2>&3)"
    source "${lang_file}"

    if [ "${keyboard}" = "${other}" ]; then
      keyboard="$(dialog --ok-button "${ok}" --cancel-button "${cancel}" --menu "${keys_msg}" 19 60 10 ${key_maps} 3>&1 1>&2 2>&3)"
      if [ "$?" -eq 0 ]; then
        break
      fi
    else
      break
    fi
  done

  localectl set-keymap "${keyboard}"
  loadkeys "${keyboard}"
  log "Set keymap to: ${keyboard}"
}
