#!/bin/sh
# Bump the version number and create a commit with the updated version
# TODO: Doesn't work with numbers larger than 9 (e.g. 1.10.1)

# Read current version from iso_version variable
CURR_SEM_VER="$(grep 'iso_version' < profiledef.sh | cut -d'=' -f2)"
CURR_LAB_VER="$(grep 'iso_label' < profiledef.sh | cut -d'=' -f2)"

# Remove extra text from version numbers
CURR_SEM_VER="$(echo "${CURR_SEM_VER}" | sed s/\"//g)"
CURR_LAB_VER="$(echo "${CURR_LAB_VER}" | sed s/ARCHROYAL// | sed s/\"//g)"

[ $# -ne 1 ] && echo "Usage: $0 [VERSION] (e.g. 'bump 0.1.1')" && exit 1

NEW_SEM_VER="$1"

# Remove all dots (.) from version number
NEW_LAB_VER="$(echo "${NEW_SEM_VER}" | sed s/\\.//g)"

# Update version numbers in profiledef.sh
sed -i.bak\
    -e "s/iso_label=\"ARCHROYAL${CURR_LAB_VER}\"/iso_label=\"ARCHROYAL${NEW_LAB_VER}\"/" \
    -e "s/iso_version=\"${CURR_SEM_VER}\"/iso_version=\"${NEW_SEM_VER}\"/" \
    profiledef.sh

echo "Bumped version number to ${NEW_SEM_VER}."
echo "Saved backup to 'profiledef.sh.bak', you can delete if you want."
